# COMMENT: This a rule for Single Page Applications
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[build]
  command = "npm run build"
  functions = "lambda"
  publish = "dist"
